language: php
dist: trusty

php:
- 7.3

matrix:
  fast_finish: true
  allow_failures:
  - php: nightly

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

install:
- travis_retry composer install --no-interaction --no-suggest

script:
- composer validate --strict
- find src tests -name '*.php' | xargs -n 1 -P4 php -l
- composer dependency-guard
- vendor/bin/phpunit --fail-on-risky
- vendor/bin/phpstan analyse --level 0 src tests
